apiVersion: backstage.io/v1alpha1
kind: Event
metadata:
 name: event-bus-dev-portal-test
 description: a place for event bus documentation
 title: Event Bus Dev Portal Test
spec:
 type: event
 lifecycle: experimental
 domain: appointments
 team: ves-event-bus 
 system: lhdi
 topics:
  - dev_test
  - staging_test
  - prod_test
 productowner: John Smith
 payload:
  id: string
  date: string
  name: string
  age: integer
  details: object
    phone: integer
    email: string
