apiVersion: backstage.io/v1alpha1
kind: EVENT
metadata:
 name: event-bus-dev-portal-test
 description: a place for event bus documentation
 title: Event Bus Dev Portal Test
spec:
 type: event
 lifecycle: experimental
 owner: ves-event-bus
 system: lhdi
 topic: dev_appointments
 domain: health 
