name: Publish to MKdocs
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '**/README.md'
  workflow_dispatch:

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.x
      - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: |
          pip install --only-binary=:all: -r requirements-lock.txt
      - run: mkdocs gh-deploy --force
